version: "3.9"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: "Y"
      TZ: "Asia/Taipei"
    volumes:
      - ./mssql.sh:/docker-entrypoint-initdb.d/mssql.sh
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
